### ISSUE TITLE
There was an error. Content-Type returned was text/xml;charset=UTF-8

### ISSUE THREAD

**Issue by askdavid** [jeichorn/Bluga.net-Webthumb-API-for-PHP#4]
In Webthumb.php in 
protected function _checkContentType($response)
there is a string comparison:
if ($response->headers['Content-Type'] != 'text/xml') {

Since the returned content type now also includes the charset information ("text/xml;charset=UTF-8") this string comparison does not work even if the content-type is 'text/xml'

suggested solution:
change: if ($response->headers['Content-Type'] != 'text/xml') {
to
if (stripos($response->headers['Content-Type'], 'text/xml') === FALSE) {

**Comment by jeichorn** [comment]
Thanks I just did an upgrade this morning which broke that.  I will get that fixed yet today.
